// Regenerates src/lib/brand/logos.ts from a Simple Icons package (CC0-1.0).
// Usage: node scripts/brand-logos.mjs <path to an unpacked simple-icons package>
import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.argv[2];
if (!root) throw new Error('Pass the unpacked simple-icons package directory.');
const SLUGS = ['youtube', 'instagram', 'tiktok', 'x', 'reddit', 'facebook', 'threads', 'googlemaps', 'google', 'googlenews', 'tripadvisor', 'yelp', 'ticketmaster', 'seatgeek', 'bandsintown', 'stubhub', 'songkick', 'wikipedia', 'wikimediacommons', 'spotify', 'uber', 'lyft', 'airbnb', 'bookingdotcom', 'expedia', 'applepodcasts'];
const data = JSON.parse(readFileSync(join(root, 'data/simple-icons.json'), 'utf8'));
const list = Array.isArray(data) ? data : data.icons;
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const rows = SLUGS.map((slug) => {
  const meta = list.find((icon) => (icon.slug ?? '') === slug);
  if (!meta) throw new Error(`No icon for ${slug}`);
  const svg = readFileSync(join(root, 'icons', `${slug}.svg`), 'utf8');
  const path = /<path d="([^"]+)"/.exec(svg)?.[1];
  if (!path) throw new Error(`No path for ${slug}`);
  return `  ${JSON.stringify(slug)}: { title: ${JSON.stringify(meta.title)}, hex: '#${meta.hex}', path: ${JSON.stringify(path)} },`;
});
writeFileSync('src/lib/brand/logos.ts', `// Generated by scripts/brand-logos.mjs from simple-icons ${version} (CC0-1.0). Do not edit by hand.
// Brand marks are shown only to say where data or a link comes from; each brand's
// trademark belongs to its owner.

export type LogoPath = { title: string; hex: string; path: string };

export const LOGOS = {
${rows.join('\n')}
} as const satisfies Record<string, LogoPath>;

export type LogoSlug = keyof typeof LOGOS;
`);
console.log(`wrote ${rows.length} logos`);
