import type { SkiRange } from './types';

/**
 * The mountain ranges the planner opens on. Season months are the usual
 * window for the range's resorts; each resort carries its own.
 */
export const RANGES: readonly SkiRange[] = [
  {
    id: 'colorado',
    name: 'Colorado Rockies',
    where: 'Colorado and New Mexico, USA',
    hemisphere: 'north',
    lat: 39.4, lng: -106.4,
    seasonMonths: [11, 12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'High, dry snow, sunny days and the most famous ski towns in America',
    colors: ['#1d3b5c', '#4fa3c7'],
    sources: ['https://en.wikipedia.org/wiki/List_of_ski_areas_and_resorts_in_the_United_States'],
  },
  {
    id: 'utah',
    name: 'Utah’s Wasatch',
    where: 'Utah, USA',
    hemisphere: 'north',
    lat: 40.6, lng: -111.6,
    seasonMonths: [11, 12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'Famously light powder, under an hour from Salt Lake City’s airport',
    colors: ['#2a2350', '#8e7cc3'],
    sources: ['https://en.wikipedia.org/wiki/Wasatch_Range'],
  },
  {
    id: 'sierra',
    name: 'Tahoe and the Sierra',
    where: 'California and Nevada, USA',
    hemisphere: 'north',
    lat: 38.6, lng: -119.6,
    seasonMonths: [11, 12, 1, 2, 3, 4, 5],
    bestMonths: [1, 2, 3],
    summary: 'Big storms, long seasons and lake views, with casinos next door',
    colors: ['#14394a', '#3fa7a0'],
    sources: ['https://en.wikipedia.org/wiki/Sierra_Nevada'],
  },
  {
    id: 'northern-rockies',
    name: 'Wyoming, Montana and Idaho',
    where: 'Northern Rockies, USA',
    hemisphere: 'north',
    lat: 44.6, lng: -111.5,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'Steep, wild and uncrowded, from Jackson Hole to Big Sky',
    colors: ['#2b2b2b', '#c8a866'],
    sources: ['https://en.wikipedia.org/wiki/Rocky_Mountains'],
  },
  {
    id: 'northeast',
    name: 'New England and Quebec',
    where: 'Northeast USA and Quebec',
    hemisphere: 'north',
    lat: 44.3, lng: -72.6,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [2, 3],
    summary: 'Classic villages, cozy inns and a short flight from the East Coast',
    colors: ['#3b1f1f', '#d9774a'],
    sources: ['https://en.wikipedia.org/wiki/Green_Mountains'],
  },
  {
    id: 'western-canada',
    name: 'Canadian Rockies and BC',
    where: 'Alberta and British Columbia, Canada',
    hemisphere: 'north',
    lat: 50.9, lng: -117.8,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'Deep snow, huge terrain and Whistler’s nightlife',
    colors: ['#173a2e', '#6faf7a'],
    sources: ['https://en.wikipedia.org/wiki/Canadian_Rockies'],
  },
  {
    id: 'french-alps',
    name: 'French Alps',
    where: 'France',
    hemisphere: 'north',
    lat: 45.4, lng: 6.6,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'The biggest linked ski areas on earth and legendary après',
    colors: ['#16264d', '#4f7bd9'],
    sources: ['https://en.wikipedia.org/wiki/French_Alps'],
  },
  {
    id: 'swiss-alps',
    name: 'Swiss Alps',
    where: 'Switzerland',
    hemisphere: 'north',
    lat: 46.4, lng: 8.2,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'The Matterhorn, glamorous towns and trains to the lifts',
    colors: ['#4a1520', '#e05a5a'],
    sources: ['https://en.wikipedia.org/wiki/Swiss_Alps'],
  },
  {
    id: 'austrian-alps',
    name: 'Austrian Alps',
    where: 'Austria',
    hemisphere: 'north',
    lat: 47.2, lng: 11.4,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'The home of après, with mountain-top concerts and good value',
    colors: ['#3a1a10', '#e4577e'],
    sources: ['https://en.wikipedia.org/wiki/Austrian_Alps'],
  },
  {
    id: 'dolomites',
    name: 'Italian Alps and Dolomites',
    where: 'Italy',
    hemisphere: 'north',
    lat: 46.5, lng: 11.6,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2, 3],
    summary: 'Pink peaks, long lunches and the 2026 Olympic slopes',
    colors: ['#402a12', '#f0a050'],
    sources: ['https://en.wikipedia.org/wiki/Dolomites'],
  },
  {
    id: 'scandinavia',
    name: 'Scandinavia and Lapland',
    where: 'Norway, Sweden and Finland',
    hemisphere: 'north',
    lat: 63.5, lng: 15,
    seasonMonths: [11, 12, 1, 2, 3, 4, 5],
    bestMonths: [2, 3, 4],
    summary: 'Northern lights, husky rides and long spring days',
    colors: ['#0f2a3a', '#7fd1c7'],
    sources: ['https://en.wikipedia.org/wiki/Scandinavian_Mountains'],
  },
  {
    id: 'japan',
    name: 'Japan',
    where: 'Hokkaido and Nagano, Japan',
    hemisphere: 'north',
    lat: 40.5, lng: 140.5,
    seasonMonths: [12, 1, 2, 3, 4],
    bestMonths: [1, 2],
    summary: 'The deepest, driest powder in the world, then hot springs and ramen',
    colors: ['#2a0f24', '#f28fb5'],
    sources: ['https://en.wikipedia.org/wiki/Skiing_in_Japan'],
  },
  {
    id: 'andes',
    name: 'The Andes',
    where: 'Chile and Argentina',
    hemisphere: 'south',
    lat: -35.5, lng: -70.3,
    seasonMonths: [6, 7, 8, 9, 10],
    bestMonths: [7, 8],
    summary: 'Skiing in summer: big Andean peaks, Chilean wine and Patagonian lakes',
    colors: ['#3a2410', '#d9a441'],
    sources: ['https://en.wikipedia.org/wiki/Andes'],
  },
  {
    id: 'oceania',
    name: 'New Zealand and Australia',
    where: 'New Zealand and Australia',
    hemisphere: 'south',
    lat: -40, lng: 160,
    seasonMonths: [6, 7, 8, 9, 10],
    bestMonths: [7, 8, 9],
    summary: 'Summer skiing with Queenstown’s adventure scene',
    colors: ['#0f2f3a', '#3db8d9'],
    sources: ['https://en.wikipedia.org/wiki/Southern_Alps'],
  },
];

export const RANGE_BY_ID = new Map(RANGES.map((range) => [range.id, range]));
