/** Ski spots on the globe → the planner's resort, so "Plan a ski trip" opens the right one. */
export const SPOT_RESORT: Readonly<Record<string, string>> = {
  'hemsedal-skiing-no': 'hemsedal',
  'trysil-skiing-no': 'trysil',
  'levi-skiing-fi': 'levi',
  'ruka-skiing-fi': 'ruka',
  'are-skiing-se': 'are',
  'chamonix-skiing-fr': 'chamonix',
  'courchevel-skiing-fr': 'courchevel',
  'zermatt-skiing-ch': 'zermatt',
  'verbier-skiing-ch': 'verbier',
  'st-anton-skiing-at': 'st-anton',
  'niseko-powder-jp': 'niseko',
  'hakuba-skiing-jp': 'hakuba',
  'queenstown-skiing-nz': 'queenstown',
  'mount-hutt-skiing-nz': 'mount-hutt',
  'aspen-snowmass-us': 'aspen-snowmass',
  'vail-us': 'vail',
  'park-city-us': 'park-city',
  'jackson-hole-us': 'jackson-hole',
  'whistler-skiing-ca': 'whistler-blackcomb',
  'bariloche-skiing-ar': 'cerro-catedral',
  'portillo-skiing-cl': 'portillo',
  'valle-nevado-skiing-cl': 'valle-nevado',
};
